name: "Ci com projeto Java para treinamento"
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Executa testes unitários
        run: mvn verify -f pom.xml